// Environment Variables
process.env.NODE_ENV = "development";
process.env.PORT = "5000";
process.env.MONGO_URI = "";
process.env.JWT_SECRET = "your_jwt_secret_key";
process.env.JWT_EXPIRE = "30d";
process.env.EMAIL_SERVICE = "gmail";
process.env.EMAIL_USERNAME = "your_email@gmail.com";
process.env.EMAIL_PASSWORD = "your_email_password";
process.env.EMAIL_FROM = "noreply@lankaphotography.com";
